name: "Fetch Language List"
author: "hugoalh"
description: "Fetch repository language list."
inputs:
  token:
    description: "{string.secret} GitHub personal access token."
    required: false
    default: "${{github.token}}"
  repository:
    description: "{string} Repository."
    required: false
    default: "${{github.repository}}"
  filter:
    description: "{string} Result filter."
    required: false
    default: "full"
  lettercase:
    description: "{string} Letter case transform."
    required: false
    default: "lower"
  format:
    description: "{string} Format."
    required: false
    default: "json"
outputs:
  language:
    description: "{(string|object.json)} Language list."
runs:
  using: "node12"
  pre: "setup.js"
  main: "main.js"
branding:
  icon: "search"
  color: "gray-dark"
